name: release

on:
  create:
    tags:

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: add version
      run: |
        export CREATE_EVENT_REF_TYPE=$(jq --raw-output .ref_type "$GITHUB_EVENT_PATH")
        export TAGNAME=$(jq --raw-output .ref "$GITHUB_EVENT_PATH")
        sed -i -e "s/{release version}/${TAGNAME}/g" style.css
    - name: create archive
      run: zip -r shifter-github-hosting-theme-sample.zip *.php *.md *.css *.txt *.png LICENSE phpcs.xml.dist inc/ js/ languages/ layouts/ template-parts/
    - name: upload
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GOPATH: /home/runner/go
      run: |
        export CREATE_EVENT_REF_TYPE=$(jq --raw-output .ref_type "$GITHUB_EVENT_PATH")
        export TAGNAME=$(jq --raw-output .ref "$GITHUB_EVENT_PATH")
        go get -u github.com/tcnksm/ghr
        ${GOPATH}/bin/ghr -replace ${TAGNAME} shifter-github-hosting-theme-sample.zip
